apiVersion: v1
kind: Service
metadata:
  name: janusgraph-cdc-service
spec:
  selector:
    app: janusgraph-cdc
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
      name: gremlin
  type: ClusterIP
